### ISSUE TITLE
[Mutations] - wrap functions

### ISSUE THREAD

**Issue by stoffern** [nodkz/graphql-compose#28]
have i misunderstood it or is it possible to wrap your own resolvers for the mutators?

Lets say a user should create a message.
He can only create the message if he is admin.
```js
MessageTC.getResolver('createOne').getFieldConfig()
```
Is it possible to expand this?

**Comment by nodkz** [comment]
For mutations I have such solution:

```js
import { GQC } from 'graphql-compose';
import { MailTC } from './mail';
import { CabinetTC } from './cabinet';
import { CabinetDataTC } from './cabinetData/cabinetData';
import { CompanyTC } from './company';
import { NoteTC } from './note';
import { CrmOrganizationTC } from './crm/organization';
import { CrmNoteTC } from './crm/note';
import { AdminTC } from './crm/admin';
import { UserTC } from './user';

export const RootMutationTC = GQC.rootMutation();

RootMutationTC.addFields({
  companyCreate: CompanyTC.get('$createOne'), // may anybody
  noteCreate: NoteTC.get('$createOne'),  // may anybody

  ...adminAccess({
    crmOrganizationCreate: CrmOrganizationTC.get('$createOne'),
    crmOrganizationUpdate: CrmOrganizationTC.get('$updateById'),
    crmOrganizationRemove: CrmOrganizationTC.get('$removeById'),
    crmNoteCreate: CrmNoteTC.get('$createOne'),
    crmNoteUpdate: CrmNoteTC.get('$updateById'),
    crmNoteRemove: CrmNoteTC.get('$removeById'),
    adminCreate: AdminTC.get('$createOne'),
    adminUpdate: AdminTC.get('$updateById'),
    adminRemove: AdminTC.get('$removeById'),
    crmTaskCreate: CrmTaskTC.get('$createOne'),
    crmTaskUpdate: CrmTaskTC.get('$updateById'),
    crmTaskRemove: CrmTaskTC.get('$removeById'),
    crmPersonCreate: CrmPersonTC.get('$createOne'),
    crmPersonUpdate: CrmPersonTC.get('$updateById'),
    crmPersonRemove: CrmPersonTC.get('$removeById'),
    userCreate: UserTC.get('$createOne'),
    userUpdate: UserTC.get('$updateById'),
    userRemove: UserTC.get('$removeById'),
    sendMail: MailTC.get('$sendMail'),
  }),
});

function adminAccess(resolvers) {
  Object.keys(resolvers).forEach((k) => {
    resolvers[k] = resolvers[k].wrapResolve(next => (rp) => {
      if (!rp.context.admin) {
        throw new Error('You should be admin, to have access to this action.');
      }
      return next(rp);
    });
  });
  return resolvers;
}
```

**Comment by stoffern** [comment]
Lets say you need to add the message to the message collection and update a connection in the user collection.
Would that be possible?

**Comment by nodkz** [comment]
This task I put on mongoose models and its hooks.

```js
NoteSchema.pre('save', function (next) {
  const note = this;
  CabinetData.findOrCreate(note.cabinetId, note.refer).then((doc) => {
    doc.lastNote = {
      msg: note.text,
      cAt: note.createdAt,
    };
    doc.save();
  }).then(() => {
    next();
  }).catch(e => next(e));
});

NoteSchema.pre('findOneAndRemove', function (next) {
  this.model.findOne(this._conditions).then((doc) => {
    if (!doc) return null;
    // find prev Note and save its data to CabinetData
    return this.model
      .findOne({
        cabinetId: doc.cabinetId,
        'refer.i': doc.refer.i,
        'refer.t': doc.refer.t,
        _id: { $ne: doc._id },
      })
      .sort({ _id: -1 })
      .then((prevDoc) => {
        const lastNote = prevDoc
          ? { msg: prevDoc.text, cAt: prevDoc.createdAt }
          : null;
        return CabinetData.findOrCreate(doc.cabinetId, doc.refer).then((cd) => {
          cd.lastNote = lastNote;
          return cd.save();
        });
      });
  })
  .then(() => next())
  .catch(() => next());
});
```

PS. But of course you may wrap mutation resolver (like above with admin access) and works directly with mongoose models.

**Comment by stoffern** [comment]
@nodkz you are awesome 😮 😉

**Comment by stoffern** [comment]
There may be one glitch here.

Lets say after you get the payload back, then there should be a object containing the new message.
But the user object should also be updated as it has a linked field to all his "owning messages" in relay.

right?

**Comment by nodkz** [comment]
Glitch? Ha! I open to you the sixth level of graphql-compose.

From mobile, so shortly:

You may add relation to output type of resolver with mutation 😈
In other words, you may extend payload with additional fields with relations.
Example will be tomorrow.

**Comment by nodkz** [comment]
Try to create such relation yourself. 
Mutation almost the same as Query in GraphQL. 

Only two diferrences:
- mutations execute sequentially (if several in one request)
- rootMutation only one level deep (can not group several mutations under some root).

**Comment by stoffern** [comment]
so you are saying i should create 2 mutations instead of 1 mutation that deals with 2 models?

**Comment by nodkz** [comment]
Oh, I think that I misunderstood you.
Please provide a real query example what you want to create and payload which want receive back.

**Comment by stoffern** [comment]
i will bring it tomorrow 😉

**Comment by stoffern** [comment]
Here we go:

Lets say Relay store on client has following 2 objects stored after query:

User Object
```js
{
  _id: 3,
  firstName: 'Elvis',
  lastName: 'Presly',
  cars: [
    {id: '1', carId: 10, owner: true, rental: false},
    {id: '2', carId: 11, owner: false, rental: true},
  ]
}
```

Car Objects
```js
{
 _id: 10,
 type: 'Ford', 
 model: 'Mondeo',
}
{
 _id: 11,
 type: 'Skoda', 
 model: 'Octavia',
}

```

What if i register a new rental car on Elvis in one mutation.
THe response should then add the new element to the Relay store, but i also need to update the User Object -> cars array.
Should i not provide all related updates after a mutation in the response payload in order to update the local Relay Store?

**Comment by nodkz** [comment]
Better to provide all needed data in payload after mutation for your Relay Store.

Eg. how I understood you should have such query:
```
mutation {
  addRentalCar(input: {
    type: "Toyota", model: "Prado:", owner: "Elvis"
  }) {
    nodeId
    record {
      id
      type
      model
    }
    ownerRecord {
      id
      cars { id carId owner rental}
    }
  }
}
```

So to construct such `mutation` you need complete following steps:
- add arg `owner` to your mutation
- wrap resolve method that will take `owner` make some work and provide needed information to payload source (which needed for next step to make proper relation)
- you should add field to `addRentalCarPayload` type via `addRelation` which will read data from payload.source and makes proper query for fetching `ownerRecord`.

If you provide me real code with mongoose models and needed mutation query, I can help you to construct it. But now it's still too difficult to answer on your question, cause you also add Relay here. First of all, I recommend determining which query we want to get. After that we can prepare server, and on next step Relay.

**Comment by stoffern** [comment]
I can not show you the real code as i am developing a highly classified app for a company.
I will create a case that looks the completely the same.

This is some of the more complex usages of the graphql-compose. i am getting a hang of everything now including the latest updates. So it will be easy to complete the docs aswell 😉

**Comment by stoffern** [comment]
It is the schema i am working on..

User Schema
```js
var UsersSchema = new mongoose.Schema({
  firstName: {type: String},
  lastName: {type: String},
  followingRestaurantIds: [{
    visited: {type: Boolean}, 
    resId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Restaurants',
      unique: true,
    }
  }],
}, {collection: 'Users' })
 

export const Users = mongoose.model('Users', UsersSchema)
export const UsersTC = composeRelay(composeMongoose(Logins))

UsersTC.addRelation(
  'followingRestaurants',
  () => ({
    resolver: RestaurantsTC.getResolver('connection'),
    args: {
      filter: (source) => ({ 
        _operators: {
          _id: {
            in: source.followingRestaurantIds.map(s => s.resId) || []
          }
        } 
      }),
    },
    projection: { followingRestaurantIds: { resId: true } },
  })
)
```

RestaurantSchema
```js
var RestaurantsSchema = new mongoose.Schema({
  firstName: {type: String},
  lastName: {type: String},
  followerIds: [{
    visited: {type: Boolean}, 
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Users',
      unique: true,
    }
  }],
}, {collection: 'Restaurants' })
 

export const Restaurants = mongoose.model('Restaurants', RestaurantsSchema)
export const RestaurantsTC = composeRelay(composeMongoose(Restaurants))

RestaurantsTC.addRelation(
  'followers',
  () => ({
    resolver: UsersTC.getResolver('connection'),
    args: {
      filter: (source) => ({ 
        _operators: {
          _id: {
            in: source.followerIds.map(s => s.userId) || []
          }
        } 
      }),
    },
    projection: { followerIds: { userId: true } },
  })
)

```

Schema
```js
RootMutationTC.addFields({
  followRestaurant: UsersTC.get('$updateById')
    .setField('restaurant', {type: GraphQLString})
    .setField('visited', {type: GraphQLBoolean})
    .wrapResolve( next => req => {
      if(req.context.userId != req.args.input.record._id)
        throw new Error ('Not allowed')

        //Add restaurant to the array in user and in restaurant.followerIds

      delete req.args.input.record.visited
      delete req.args.input.record.restaurant
      return next(req)
    }),
})
```

Mutation
```js
mutation {
  userUpdate(input: {clientMutationId: "test", record: {_id: "1", restaurant: "100", "visited": true}}) {
    recordId
    nodeId
    record {
      firstName
      lastName
      followingRestaurantIds{
        visited
        resId
      }
    }
    restaurant{
      followerIds
      followers{
        _id
      }
    }
  }
}

```

**Comment by nodkz** [comment]
Not so easy solution. Comments inside.

```js

var RestaurantsSchema = new mongoose.Schema({
  firstName: {type: String},
  lastName: {type: String},
  followerIds: [{
    visited: {type: Boolean}, 
    userId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Users',
      unique: true,
    }
  }],
}, { collection: 'Restaurants' })


export const Restaurants = mongoose.model('Restaurants', RestaurantsSchema)
export const RestaurantsTC = composeRelay(composeMongoose(Restaurants))

RestaurantsTC.addRelation(
  'followers',
  () => ({
    resolver: UsersTC.getResolver('connection'),
    args: { 
      filter: (source) => ({ 
        _id: { $in: source.followerIds.map(s => s.userId) || [] }
      }),
    },
    projection: { followerIds: { userId: true } },
  })
);
```
user file
```js
var UsersSchema = new mongoose.Schema({
  firstName: {type: String},
  lastName: {type: String},
  followingRestaurantIds: [{
    visited: {type: Boolean}, 
    resId: {
      type: mongoose.Schema.Types.ObjectId,
      ref: 'Restaurants',
      unique: true,
    }
  }],
}, {collection: 'Users' })


export const Users = mongoose.model('Users', UsersSchema)
export const UserWORelayTC = composeMongoose(Logins) // Logins??? ;)

// I recommend to create additional resolver with mutation in USER file not in RootMutation
// Here we add resolver before `composeRelay` 
//    cause I do not want create input field for args and clientMutationId by hands 
// In future I planned rewrite `composeRelay`, such way that apply it only to RootQuery and RootMutation 
//    and it recursevly change all types
import { GraphQLMongoID } from 'graphql-compose-mongoose';
UserWORelayTC.addResolver({
  name: 'followRestaurant',
  kind: 'mutation', // needs for Relay Wrapper to add clientMutationId and move args to input field
  outputType: TypeComposer.create({
    name: 'FollowRestaurant',
    fields: {
      recordId: 'ID',
      record: UserWORelayTC,
      restaurant: RestaurantsTC,
    },
  }), 
  args: {
    _id: GraphQLMongoID, // or may leave it as 'String'
    restaurant: 'String',
    visited: 'Boolean',
  },
  resolve: async ({ args, context }) => {
    // You may use resolvers directly and in different combinations
    //   UserWORelayTC.get('$updateById').resolve({ args: {}, projection: {projection.record} }).then() ...
    //   But it not stable yet and too much magic and of course ugly
    
    // So just write your updates by hands, it more clearly

    if(context.userId != args._id)
        throw new Error ('Not allowed')

    const user = await User.findById(args._id);
    const rest = await Restaurants.findById(args.restaurant);

    if (args.visited) {
      // change data in model when visit
    } else {
      // change data in model when unvisit
    }

    await user.save();
    await rest.save();
    
    return {
      record: user,
      recordId: user._id,
      restaurant: rest,
    };
  }
});

export const UsersTC = composeRelay(UserWORelayTC)

UsersTC.addRelation(
  'followingRestaurants',
  () => ({
    resolver: RestaurantsTC.getResolver('connection'),
    args: {
      // in relations args.filter we may pass mongoose query directly 
      // (do not use _operators it may be depricated in future due Resolver.addFilter())
      filter: (source) => ({ 
        _id: {
          $in: source.followingRestaurantIds.map(s => s.resId) || []
        }
      }),
    },
    // FYI this is valid record 
    //    but mongoose does not understand deep/nested projections
    //    so internally I pass to it { followingRestaurantIds: 1 } ;)
    // Soooo for performance reasons try to avoid BIG nested objects in MongoDB
    //    but it may improve (add support for nesting projection) in mongo 3.6
    projection: { followingRestaurantIds: { resId: true } }, 
  })
);
```
root:
```js
RootMutationTC.addFields({
  followRestaurant: UsersTC.get('$followingRestaurants'),
})
```

Mutation should be:
```
mutation {
  followRestaurant(input: {clientMutationId: "test", _id: "1", restaurant: "100", "visited": true }) {
    recordId
    nodeId
    record {
      firstName
      lastName
      followingRestaurantIds{
        visited
        resId
      }
    }
    restaurant{
      followerIds
      followers{
        _id
      }
    }
  }
}
```

**Comment by stoffern** [comment]
A huge thanks for the response and example.
Would you solve this problem in other ways? as you would need to query either restaurant or user at some point to get data about follower.

**Comment by stoffern** [comment]
This fails..
Any ideas?


```js
importing {RestuarantTC} from './Restaurant'

UserWORelayTC.addResolver({
  name: 'followRestaurant',
  kind: 'mutation', // needs for Relay Wrapper to add clientMutationId and move args to input field
  outputType: TypeComposer.create({
    name: 'FollowRestaurant',
    fields: {
      recordId: 'ID',
      record: UserWORelayTC,
      restaurant: RestaurantsTC,
    },
  }), 
  args: {
    _id: GraphQLMongoID, // or may leave it as 'String'
    restaurant: 'String',
    visited: 'Boolean',
  },
  resolve: async ({ args, context }) => {
   //some data..
  }
})
```

```
D:\dev\node_modules\graphql-compose\lib\typeMapper.js:157                                                               
      if (fieldConfig instanceof _inputTypeComposer2.default || fieldConfig.type instanceof _inputTypeComposer2.default) {             
                                                                           ^                                                           
                                                                                                                                       
TypeError: Cannot read property 'type' of undefined                                                                                    
    at TypeMapper.convertOutputFieldConfig (D:\dev\node_modules\graphql-compose\lib\typeMapper.js:157:76)               
    at D:\dev\node_modules\graphql-compose\lib\typeMapper.js:201:30                                                     
    at Array.forEach (native)                                                                                                          
    at TypeMapper.convertOutputFieldConfigMap (D:\dev\node_modules\graphql-compose\lib\typeMapper.js:200:35)            
    at TypeComposer.setFields (D:\dev\node_modules\graphql-compose\lib\typeComposer.js:162:50)                          
    at TypeComposer.addFields (D:\dev\node_modules\graphql-compose\lib\typeComposer.js:201:12)                          
    at Function.create (D:\dev\node_modules\graphql-compose\lib\typeComposer.js:114:14)                                 
    at Object.<anonymous> (D:/dev/Shopsii/server/src/models/Restaurant.js:91:28)                                                           
    at Module._compile (module.js:541:32)                                                                                              
    at loader (D:\dev\node_modules\babel-register\lib\node.js:144:5)                                                    
    at Object.require.extensions.(anonymous function) [as .js] (D:\dev\node_modules\babel-register\lib\node.js:154:7)   
    at Module.load (module.js:458:32)                                                                                                  
    at tryModuleLoad (module.js:417:12)                                                                                                
    at Function.Module._load (module.js:409:3)                                                                                         
    at Module.require (module.js:468:17)                                                                                               
    at require (internal/module.js:20:19)                                                                                              
error Command failed with exit code 1.                                                                                         
```

**Comment by nodkz** [comment]
Agr. 
Suppose that it is **hoisting** problem - two types imports each other.
So `outputType` can not be constructed properly. 

Method `addRelation` uses arrow function for solving hoisting problem. But how to do it with `addResolver` I'll think. Do not have hotfix for such problem.

Your fast solutions: 
1. Move `UserWORelayTC.addResolver({` to 3rd file:
```js
import {RestaurantsTC} from './Restaurant';
import {UserWORelayTC} from './User';

UserWORelayTC.addResolver({
...
```
2. Or add `restaurant: RestaurantsTC,` later. Eg. extend this resolver right before schema build.

**Comment by stoffern** [comment]
@nodkz i have never heard of the hoisting problem before you mentioned it..
Now it all makes sense! 😮 

I have solved this problem in another way, just made Relay force fetch new updates to users local data.

Well do you think this issue should be addressed so we can edit the outputType with multiple TCs attached?

**Comment by nodkz** [comment]
Got yesterday in browser console that component is undefined. It also was hoisting problem with imports, some components use each other. So had a great refactoring:
<img width="563" alt="screen shot 2016-11-10 at 17 25 03" src="https://cloud.githubusercontent.com/assets/1946920/20174969/c8269a90-a76a-11e6-8fb2-33932f947c0a.png">
Right to the end starts to work properly (after editing file # 134).

PS. Recommend to use eslint plugin https://github.com/benmosher/eslint-plugin-import

---
I think that somehow `addRelation` method should be used for solving this problem. We can right now to call this method on `outputType` but needs to play with it. So I think that's no need in addressing.

**Comment by stoffern** [comment]
nice, did you use `eslint-plugin-import` to find and fix your hoisting problems?

**Comment by nodkz** [comment]
Nope. It's too simple to find such problems. It makes just basiс checks, eg. file existence, correct order definition and the bunch of other checks (see its repo).
